[project]
name = "event-registry"
description = "Event Registry Clarity contracts for Hiro Git Projects deployment"
authors = ["edison-alpha"]
telemetry = true
cache_dir = "./.cache"

[contracts.event-registry]
path = "contracts/event-registry.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
